name: repo2jupyterlite-action
branding:
  icon: code
  color: yellow
description: |
  Publish a JupyterLite static site (with pre-installed packages) to GitHub pages.

inputs:
  destination_path:
    description: Local path where static JupyterLite files will be published
    required: true
    default: ./dist

runs:
  # We just want to call a bunch of other steps
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        # Use conda-forge only everwhere, we don't need defaults at all
        miniforge-version: latest
        # Use mambaa, required for Xeus-Python integration
        mamba-version: "*"
        use-mamba: true
    - name: Install repo2jupyterlite
      shell: bash -l {0}
      run: |
        # FIXME: install this from a published package
        python -m pip install git+https://github.com/yuvipanda/repo2jupyterlite@main
    - name: Build the JupyterLite site
      shell: bash -l {0}
      run: |
        # Build the jupyterlite!
        repo2jupyterlite . ${{ inputs.destination_path }}