name: repo2jupyterlite-action
branding:
  icon: code
  color: yellow
description: |
  Publish a JupyterLite static site (with pre-installed packages) to GitHub pages.

inputs:
  contents_path:
    description: Local path containing contents to be built into the JupyterLite
    required: true
    default: .
  destination_path:
    description: Local path where static JupyterLite files will be published
    required: true
    default: ./dist
  repo2jupyterlite_version:
    description: |
      Version of repo2jupyterlite to use.

      'stable' installs latest version from PyPI, 'latest' installs latest version
      from the repo2jupyterlite git repository, any other string installs that specific
      version from PyPI
    default: stable
    required: true

runs:
  # We just want to call a bunch of other steps
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        # Use conda-forge only everwhere, we don't need defaults at all
        miniforge-version: latest
        # Use mambaa, required for Xeus-Python integration
        mamba-version: "*"
        use-mamba: true
    - name: Install repo2jupyterlite
      # Needed to use the installed mamba
      # We also write this in python, as I'm not smart enough to do conditionals
      # in bash. The `-u` to python makes output unbuffered so print statements
      # come out corectly. {0} is replaced with path to file containing the contents
      # of `run`
      shell: bash -l -c "python -u {0}"
      run: |
        import sys

        version = '${{ inputs.repo2jupyterlite_version }}'
        if version == 'stable':
          package = 'repo2jupyterlite'
        elif version == 'latest':
          package = 'git+https://github.com/yuvipanda/repo2jupyterlite@main'
        else:
          package = f'repo2jupyterlite@{version}'

        print(f"Installing {package}")
        import subprocess
        subprocess.check_call([
          sys.executable,
          '-m',
          'pip', 'install', package
        ])
    - name: Build the JupyterLite site
      # Needed to use the installed mamba
      shell: bash -l {0}
      run: |
        # Build the jupyterlite!
        repo2jupyterlite ${{ inputs.contents_path }} ${{ inputs.destination_path }}