name: Build & Publish a JupyterLite

inputs:
  destination_path:
    description: Local path where static JupyterLite files will be published
    required: true
    default: ./dist

runs:
  using: "composite"
  runs-on: ubuntu-latest
  defaults:
    run:
      shell: bash -l {0}
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniforge-version: latest
        mamba-version: "*"
        use-mamba: true
    - name: Install repo2jupyterlite
      run: |
        python -m pip install git+https://github.com/yuvipanda/repo2jupyterlite@main
    - name: Build the JupyterLite site
      run: |
        repo2jupyterlite . ${{ inputs.destination_path }}